on: pull_request

jobs:
  example_comment_pr:
    needs: build
    runs-on: ubuntu-latest
    name: Link Sonar Quality Gate into PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Please check Sonar Quality Gate at https://sonarqube.inria.fr/sonarqube/dashboard?id=youennmerel%3Ashanoir-ng&pullRequest=${{ github.event.number }}
