# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch the master branch
      run: git fetch --no-tags --no-recurse-submodules --depth=1 origin +refs/heads/master:refs/remotes/origin/master
    - name: check migration names
      run: cd docker-compose/database && ./check_migration_names.py
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache SonarQube packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Create directory /shanoir-ng-logs
      run: sudo mkdir -m777 /var/log/shanoir-ng-logs
    - name: Build with Maven
      run: mvn -f ./shanoir-ng-parent/pom.xml install verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=youennmerel:shanoir-ng
      env:
        SHANOIR_URL_HOST: localhost
        SHANOIR_URL_SCHEME: http
        SHANOIR_PREFIX: github
        SHANOIR_ADMIN_EMAIL: nobody@inria.fr
        SHANOIR_KEYCLOAK_USER: admin
        SHANOIR_KEYCLOAK_PASSWORD: '&a1A&a1A'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
